-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: localhost
-- Generation Time: Feb 05, 2024 at 04:22 PM
-- Server version: 8.0.34
-- PHP Version: 8.2.10

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `stud_38613013`
--

-- --------------------------------------------------------

--
-- Table structure for table `articles`
--

CREATE TABLE `articles` (
  `id` int NOT NULL,
  `name` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `content` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `likes` int NOT NULL DEFAULT '0',
  `dislikes` int NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Dumping data for table `articles`
--

INSERT INTO `articles` (`id`, `name`, `content`, `likes`, `dislikes`) VALUES
(1, 'Security', '; rozbije sa to? Tot otazka', 26, 20),
(2, 'Oh the shamelessness!', '<a href=\"https://skodapetr.github.io/projects-ideas\">projects ideas</a>        ', 2, 2),
(3, 'Web App Error Handling', 'Effective strategies for handling errors in web applications.', 0, 1),
(4, 'Web Application Logging', 'Implementing robust logging mechanisms for better error tracking.', 0, 0),
(5, 'Ten Šmrnc', 'Ty vieš, že mám ten šmrnc, tú rizzness\r\nZjem ťa na jeden hlt, moja rizzness\r\nSadni a počúvaj (sit down, shut up, sit down, shut up)\r\nSadni a počúvaj (sit down, shut up, sit down)\r\nOoh, sadni a počúvaj\r\n\r\nPozerám sa na teba zhora, up on the Boeing\r\nYeah, arogantné oči sa neboja\r\nHey, what you doin\'?\r\nVšetci využívajú svoje slabosti bez žiadnych ohľadov, zoom in\r\nRastúca pain, pain, pain\r\nWhat you gonna gain, gain, gain?\r\n\r\nDav ľudí push a ľahko skreslia, skutočnú povahu slov menia\r\nPresne ako mincou flip that, schovaj za sebou pravdu ihneď\r\nŠepot sa rozšíril, aj keď som môj hlas stíšil\r\nVšetko same, same, same, štruktúrovaná game, game, game\r\n\r\nYeah, veľa veľa\r\nFakt veľa mätúcich slov\r\nDon\'t really care, všetko je pre mňa smiešnô\r\nYeah, nebavia ma tie pravdepodobné lži\r\nPočúvam len seba a svoje slovo\r\n\r\ndsadsadasd', 1, 0),
(6, 'Web Dev Workflow Optimization', 'Optimizing your development workflow for increased productivity and code quality. Explore tools and techniques to streamline your processes and enhance collaboration among team members. This article covers everything from code reviews to automated testing and continuous integration practices. Learn how to strike the right balance between speed and code reliability in your web development projects. This article has been generated by ChatGPT.', 1, 0),
(7, 'Web App Deployment Strategies', 'Delve into different deployment strategies to ensure a smooth and reliable deployment process for your web applications. From blue-green deployments to canary releases, discover methods to minimize downtime and roll back changes if necessary. Understand the importance of containerization and orchestration in modern deployment practices. This article provides insights into creating a robust deployment pipeline. This article has been generated by ChatGPT.', 1, 0),
(8, 'Web App Analytics for Success', 'Unlock the power of web analytics to gather valuable insights into user behavior and enhance your web applications. Learn how to set up and configure analytics tools effectively. Explore metrics such as user engagement, conversion rates, and bounce rates to make data-driven decisions. Understand the importance of A/B testing in optimizing your web app\'s performance. This article provides a comprehensive guide to leveraging analytics for success. This article has been generated by ChatGPT.', 0, 1),
(9, 'Web Design: Beyond Aesthetics', 'Move beyond aesthetics and delve into the principles of effective web design. Explore the psychology of color, typography, and layout to create visually appealing and user-friendly interfaces. Learn how to balance creativity with functionality for a seamless user experience. Understand the significance of responsive design in today\'s multi-device landscape. This article equips you with the knowledge to elevate your web design skills. This article has been generated by ChatGPT.', 1, 0),
(10, 'Web App Security: Beyond Basics', 'Go beyond the basics of web application security and delve into advanced techniques to fortify your applications. Explore topics such as penetration testing, threat modeling, and secure coding practices. Learn how to implement security headers, SSL/TLS, and secure session management. Understand the importance of regular security audits and updates. This article provides an in-depth guide to enhancing your web app security. This article has been generated by ChatGPT.', 1, 0),
(11, 'Web App Performance Tuning', 'Optimize the performance of your web applications by delving into advanced tuning techniques. Explore browser rendering optimizations, lazy loading, and efficient image handling. Learn about server-side optimizations, such as caching strategies and load balancing. Understand the impact of third-party scripts on performance and how to manage them. This article offers practical tips to boost your web app\'s speed and responsiveness. This article has been generated by ChatGPT.', 27, 1),
(12, 'Web App Monetization Strategies', 'Explore various strategies to monetize your web applications effectively. From freemium models to subscription plans, discover approaches that align with your business goals. Learn about in-app purchases, advertising, and affiliate marketing as revenue streams. Understand the importance of user engagement and providing value to users. This article guides you through the landscape of web app monetization. This article has been generated by ChatGPT.', 0, 0),
(13, 'Web App User Onboarding', 'Craft a seamless and engaging user onboarding experience for your web applications. Learn the art of creating user-friendly tutorials, tooltips, and interactive guides. Understand the importance of user feedback and iterate on the onboarding process. Explore strategies to reduce friction and enhance user retention. This article provides practical insights to ensure a positive onboarding journey. This article has been generated by ChatGPT.', 0, 0),
(14, 'Web App Push Notifications', 'Implement effective push notification strategies to keep users engaged with your web applications. Explore the power of timely and relevant notifications to drive user interactions. Learn about browser support, permission management, and best practices for push notifications. Understand how to personalize notifications for a tailored user experience. This article offers a comprehensive guide to leveraging push notifications in web development. This article has been generated by ChatGPT.', 0, 0),
(15, 'Web App Gamification Revisited', 'Revisit the concept of gamification and its impact on user engagement in web applications. Explore new trends and innovative approaches to integrating game elements. Learn about point systems, badges, and other gamification techniques to motivate users. Understand the psychology behind gamification and its influence on user behavior. This article provides fresh insights into enhancing user engagement through gamification. This article has been generated by ChatGPT.', 0, 0),
(16, 'Web App SEO Best Practices', 'Optimize your web applications for search engines with effective SEO practices. Explore on-page and off-page optimization strategies to improve your site\'s visibility. Learn about keyword research, meta tags, and mobile optimization for search engine ranking. Understand the importance of high-quality content and backlinks. This article equips you with actionable tips to boost your web app\'s SEO performance. This article has been generated by ChatGPT.', 0, 0),
(17, 'Web App Branding Essentials', 'Establish a strong and memorable brand identity for your web applications. Explore the elements of effective branding, including logo design, color schemes, and typography. Learn how to create a consistent brand experience across your web app and marketing materials. Understand the impact of branding on user trust and loyalty. This article provides practical insights into building a compelling web app brand. This article has been generated by ChatGPT.', 0, 0),
(18, 'Web App Cross-Browser Testing', 'Ensure compatibility and a seamless user experience across different browsers with effective cross-browser testing. Explore popular testing tools and techniques to identify and fix compatibility issues. Learn how to test on various browsers and versions to catch potential problems early in the development process. This article guides you through the essentials of cross-browser testing for web applications. This article has been generated by ChatGPT.', 0, 0),
(19, 'Web App User Feedback Strategies', 'Implement strategies to gather valuable user feedback and insights for continuous improvement. Explore user surveys, feedback forms, and analytics tools to understand user preferences. Learn how to encourage users to provide constructive feedback and iterate based on their responses. Understand the importance of responsive customer support. This article offers practical tips for enhancing user feedback strategies in your web applications. This article has been generated by ChatGPT.', 0, 0),
(20, 'Web App Internationalization', 'Prepare your web applications for a global audience by implementing internationalization strategies. Explore techniques for adapting your content to different languages and cultures. Learn about language files, date and time formatting, and currency localization. Understand the importance of cultural sensitivity in user interfaces. This article provides insights into creating web applications that cater to diverse international audiences. This article has been generated by ChatGPT.', 0, 0),
(21, 'Web App Data Privacy Compliance', 'Navigate the landscape of data privacy compliance for your web applications. Explore regulations such as GDPR and CCPA and understand their implications. Learn about user consent, data protection policies, and secure data storage practices. Discover how to implement features like cookie banners and privacy dashboards. This article guides you through ensuring data privacy in your web applications. This article has been generated by ChatGPT.', 0, 0),
(22, 'User Retention Strategies', 'Develop effective strategies to retain users and build long-term engagement with your web applications. Explore personalized content, loyalty programs, and targeted communication to keep users coming back. Learn about the impact of user experience on retention and the importance of customer satisfaction. This article provides practical tips to enhance user retention in your web applications. This article has been generated by ChatGPT.', 0, 0),
(23, 'Web App Progressive Enhancement', 'Adopt a progressive enhancement approach to web development for improved accessibility and user experience. Explore the concept of providing a baseline experience and enhancing it based on the capabilities of the user\'s device. Learn about feature detection, graceful degradation, and building robust, future-proof web applications. This article guides you through the principles of progressive enhancement in web development. This article has been generated by ChatGPT.', 0, 0),
(24, 'Web App Accessibility Testing', 'Ensure your web applications are accessible to all users by incorporating effective accessibility testing. Explore automated and manual testing techniques to identify and address accessibility issues. Learn about ARIA roles, keyboard navigation, and screen reader compatibility. Understand the impact of color contrast and font choices on accessibility. This article provides insights into prioritizing accessibility in your web development process. This article has been generated by ChatGPT.', 0, 0),
(25, 'Machine Learning Integration', 'Explore the integration of machine learning into your web applications for enhanced functionality. Learn about recommendation systems, natural language processing, and predictive analytics. Understand the potential of machine learning in user personalization and content optimization. Discover tools and frameworks for implementing machine learning models in web development. This article guides you through the possibilities of machine learning integration. This article has been generated by ChatGPT.', 0, 0),
(26, 'Web App Virtual Reality (VR)', 'Explore the world of virtual reality and its potential applications in web development. Learn about WebVR and WebXR standards for creating immersive experiences. Understand the challenges and opportunities of integrating VR into your web applications. Discover tools and frameworks for building VR-enhanced web content. This article provides insights into the exciting possibilities of virtual reality in web development. This article has been generated by ChatGPT.', 0, 0),
(27, 'Web App Cloud Integration', 'Integrate cloud services seamlessly into your web applications for enhanced scalability and flexibility. Explore cloud storage, serverless computing, and cloud-based databases. Learn about the benefits of using services like AWS, Azure, and Google Cloud in web development. Understand the importance of security and compliance when working with cloud solutions. This article guides you through effective cloud integration strategies for web applications. This article has been generated by ChatGPT.', 0, 0),
(28, 'Web App Blockchain Integration', 'Explore the integration of blockchain technology into your web applications for enhanced security and transparency. Learn about smart contracts, decentralized applications (DApps), and blockchain-based authentication. Understand the potential impact of blockchain on data integrity and user trust. Discover tools and frameworks for implementing blockchain solutions in web development. This article guides you through the possibilities of blockchain integration. This article has been generated by ChatGPT.', 0, 0),
(29, 'Web App Chatbot Implementation', 'Enhance user interaction and support in your web applications through the implementation of chatbots. Explore natural language processing, conversation design, and integration with messaging platforms. Learn about the benefits of chatbots in customer service and user engagement. Understand how to create personalized and context-aware chatbot experiences. This article provides insights into the effective implementation of chatbots in web development. This article has been generated by ChatGPT.', 0, 0),
(30, 'User Authentication Evolution', 'Explore the evolution of user authentication in web development. Learn about passwordless authentication, biometric authentication, and multi-factor authentication. Understand the importance of security in user authentication and the risks associated with traditional methods. Discover modern authentication standards and frameworks. This article guides you through the advancements in user authentication for web applications. This article has been generated by ChatGPT.', 0, 0),
(38, 'Pokazi sa to?', 'Zatial nie', 0, 0);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `articles`
--
ALTER TABLE `articles`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `articles`
--
ALTER TABLE `articles`
  MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=39;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
