services:
  #db:
  #  image: mariadb
  #  env_file:
  #    - .env
  #  ports:
  #    - "3306:3306"
  #  volumes:
  #    - "./articles-mysql.sql:/docker-entrypoint-initdb.d/1.sql"
  #    - maria_data:/var/lib/mysql
  db:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - "./articles-pgsql.sql:/docker-entrypoint-initdb.d/init.sql"
      - postgres_data:/var/lib/postgresql/data/

  app:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8080:80"
    depends_on:
      - db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

volumes:
  maria_data:
  postgres_data:
